src/ilmo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf.urls.i18n import i18n_patterns
from .views import *

urlpatterns = i18n_patterns(
    path('', RedirectView.as_view(url='library/', permanent=True)),
    path('library/', include('library.urls')),
    path('admin/', admin.site.urls, name="admin"),
    path("accounts/", include("django.contrib.auth.urls")),
    path(".well-known/security.txt", security_txt),
    path("api-auth/", include('rest_framework.urls')),
    prefix_default_language=False
)

src/library/api/urls.py
from django.urls import path
from .views import (
    BookApiView,
    AccessControlApiView
)

urlpatterns = [
    path('book', BookApiView.as_view()),
    path('uid/<slug:uk>/room/<uuid:rk>', AccessControlApiView.as_view(), name='access-check'),
]

src/library/urls.py
from django.urls import path, include

from . import views

app_name = "library"

""" BOOK """
urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
    # ex: /books/
    path('books/', views.BookListView.as_view(), name='books'),
    # ex: /library/books/5/
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    # ex: /library/books/5/loans/
    path('books/<int:pk>/loans/', views.loans_of_book),
    # ex: /library/bookInstance/a6c3b3ae-b254-4480-8573-95868068a9c3/
    path('bookInstance/<slug:pk>', views.BookInstanceDetailView.as_view(), name='bookInstance-detail'),

    # ex: /library/author/5/
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
]

""" MATERIAL """
urlpatterns += [
    # ex: /material/
    path('materials/', views.MaterialListView.as_view(), name='materials'),
    # ex: /library/material/5/
    path('material/<int:pk>', views.MaterialDetailView.as_view(), name='material-detail'),
    # ex: /library/materialInstance/a6c3b3ae-b254-4480-8573-95868068a9c3/
    path('materialInstance/<slug:pk>', views.MaterialInstanceDetailView.as_view(),
        name='materialInstance-detail'),
]

""" LOANS """
urlpatterns += [
    # ex: /library/my-loans/
    path('my-loans/', views.list_loans_of_user, name='my-loans'),
    # ex: /library/loaned-items/
    path('loaned-items/', views.list_loans_unreturned, name='loaned-items'),
    # ex: /library/loan/1/
    path('loan/<int:pk>/', views.LoanDetailView.as_view(), name='loan-detail'),
]

""" BORROW """
urlpatterns += [
    # ex: /library/item/a6c3b3ae-b254-4480-8573-95868068a9c3/borrow/
    path('item/<uuid:pk>/borrow/', views.borrow_item, name='item-borrow'),
    # ex: /library/item/a6c3b3ae-b254-4480-8573-95868068a9c3/borrow/user/5
    path('item/<uuid:ik>/borrow/user/<slug:uk>', views.borrow_user, name='user-borrow'),
    path('item/<uuid:ik>/return', views.return_item, name='item-return'),
]

""" ITEM """
urlpatterns += [
    path('item/<uuid:pk>/renew/', views.renew_item_librarian, name='renew-item-librarian'),
    path('item/search/', views.item_search, name='item-search'),
]

""" SEARCH """
urlpatterns += [
    path('search/', views.search, name='search'),
]


""" AUTHOR """
urlpatterns += [
    # ex: /library/authors/
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    # ex: /library/author/create/
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

""" OPENING HOUR """
urlpatterns += [
    # ex: /library/openinghour/create
    path('openinghour/create', views.OpeningHoursCreateView.as_view(), name='openinghour-create'),
    # ex: /library/<int:pk>/delete
    path('openinghour/<int:pk>/delete', views.OpeningHourDeleteView.as_view(), name='openinghour-delete'),
    # ex: /library/openinghours/
    path('openinghours/', views.OpeningHoursListView.as_view(), name='openinghours'),
]

""" ACCOUNTS """
urlpatterns += [
    path('user-detail/<slug:pk>/', views.user_detail, name='user-detail'),
    path('my-profile/', views.my_profile, name='my-profile'),
    path('accounts/', include('django.contrib.auth.urls')),
]

""" Metrics """
urlpatterns += [
    # ex: /library/metrics
    path('metrics/', views.metrics, name="metrics"),
]

""" API """
urlpatterns += [
    path('api/', include('library.api.urls')),
]

src/library/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid
from datetime import date
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.db.models.signals import post_save
from django.db import models
from django.dispatch import receiver
from datetime import datetime, timedelta
from polymorphic.models import PolymorphicModel


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text=_('Enter a book genre (e.g. Science Fiction)'), verbose_name=_('Name'))

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    class Meta:
        verbose_name=_('Genre')
        verbose_name_plural=_('Genre')


class Material(models.Model):
    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('library:material-detail', args=[str(self.id)])

    name = models.CharField(max_length=200)

    class Meta:
        verbose_name=_('Material')
        verbose_name_plural=_('Materials')


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100, verbose_name=_('First name'))
    last_name = models.CharField(max_length=100, verbose_name=_('Last name'))
    date_of_birth = models.DateField(null=True, blank=True, verbose_name=_('Date of birth'))
    date_of_death = models.DateField(null=True, blank=True, verbose_name=_('Date of death'))

    def __str__(self):
        """String for representing the Model object."""
        if self.first_name != "":
            return f'{self.first_name} {self.last_name}'
        else:
            return self.last_name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('library:author-detail', args=[str(self.id)])

    class Meta:
        ordering = ['last_name', 'first_name']
        permissions = (("can_modify_author", _("Can add, update or delete an author")),)
        verbose_name=_('Author')
        verbose_name_plural=_('Authors')


class Book(models.Model):
    title = models.CharField(max_length=200, verbose_name=_('Titel'))
    author = models.ManyToManyField(Author, help_text=_('Select the autor(s) of this book.'), verbose_name=_('Author'))
    genre = models.ManyToManyField(Genre, help_text=_('Select a genre for this book.'), verbose_name=_('Genre'))
    summary = models.TextField(max_length=1000, help_text=_('Enter a brief description of the book.'), verbose_name=_('Summary'))
    isbn = models.CharField(max_length=13, null=True, help_text=_('ISBN number (13 Characters)'), verbose_name=_('ISBN'))
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True, verbose_name=_('Language'))

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('library:book-detail', args=[str(self.id)])

    class Meta:
        verbose_name=_('Book')
        verbose_name_plural=_('Books')

class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text=_("Enter a natural languages name (e.g. English, French, Japanese etc.)."),
                            unique=True)

    languagecode = models.CharField(max_length = 10,
                                # Translators: This helptext includes an URL
                                help_text = _("Enter the language code for this language. For further information see  http://www.i18nguy.com/unicode/language-identifiers.html"),
                                verbose_name=_('Language code'))


    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

    class Meta:
        verbose_name=_('Language')
        verbose_name_plural=_('Languages')


class Member(models.Model):
    user = models.OneToOneField(User,  on_delete=models.CASCADE, verbose_name=_('User'))
    preferred_language = models.ForeignKey(Language, on_delete=models.PROTECT, null=True, verbose_name=_('Preffered language'))
    UID = models.CharField(max_length=50, blank=True, help_text=_("The UID of a NFC chip (e.g. in a student id)."), verbose_name=_('UID'))

    @receiver(post_save, sender=User)
    def add_member(sender, instance, created, raw, using, **kwargs):
        if len(Member.objects.filter(user=instance)) != 1:
            Member.objects.create(user=instance)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse("library:user-detail", args=[str(self.user.id)])

    class Meta:
        verbose_name=_('Member')
        verbose_name_plural=_('Members')


class Item(PolymorphicModel):
    """Represents an item that is physically in the library"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text=_('Unique ID for this particular item across whole library.'),
                          verbose_name=_('Id'))
    label = models.CharField(max_length=20, unique=True, verbose_name=_('Label'))

    LOAN_STATUS = (
        ('m', _('Maintenance')),
        ('o', _('On loan')),
        ('a', _('Available')),
        ('r', _('Reserved')),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text=_('Item availability'),
    )

    class Meta:
        permissions = (("can_mark_returned", _("Set item as returned")),
                       ("can_see_borrowed", _("See all borrowed items")))
        verbose_name=_('Item')
        verbose_name_plural=_('Items')

    def __str__(self):
        return str(f"[{self.label}]")

    def borrow(self,
               borrower: Member,
               due_back=timezone.now() + timezone.timedelta(days=28),
               lent_on=timezone.now()):
        """
        Borrows the item by marking it as on loan and creating a loan

        Parameters
        ----------
        borrower:User The user that borrows the item
        due_back:datetime When the item has to be returned, default is one month later
        lent_on:datetime When the item was lent. Parameter most useful for testing

        Returns
        -------
        None
        """
        l = Loan.objects.create(
            item=self,
            lent_on=lent_on,
            due_back=due_back,
            borrower=borrower,
        )
        l.save()
        # Set status to on loan
        self.status = "o"
        self.save()

    def return_item(self,
                    return_date=timezone.now()) -> bool:
        """
        Sets the item as available and mark the loan as returned

        The st
        Parameters
        ----------
        return_date:datetime=timezone.now()
            Defaults to now, but it is possible to use a custom return date (e.g. to avoid late fees when returned over weekend)

        Returns
        -------
        bool True if successful, else false
        """
        try:
            unreturned_loan_of_item = Loan.objects.filter(item=self,
                                                          returned_on=None)[0]
        except IndexError:
            return False
        unreturned_loan_of_item.returned_on = return_date
        unreturned_loan_of_item.save()
        # Set status to available
        self.status = "a"
        self.save()
        return True

    @property
    def borrower(self):
        """ Returns the current borrower or 'Not borrowed'"""
        try:
            last_loan = Loan.objects.filter(item=self).latest("lent_on")
            if last_loan.returned:
                raise Loan.DoesNotExist
            else:
                return last_loan.borrower
        except Loan.DoesNotExist:
            # Translators: Is shown instead of a person that borrowed the item
            return _("Not borrowed")

    @property
    def due_back(self):
        """ Returns the current due date or 'Not borrowed'"""
        try:
            last_loan = Loan.objects.filter(item=self).latest("lent_on")
            if last_loan.returned:
                raise Loan.DoesNotExist
            else:
                return last_loan.due_back
        except Loan.DoesNotExist:
            # Translators: Is shown instead of a person that borrowed the item
            return _("Not borrowed")

    @due_back.setter
    def due_back(self, value):
        """ Sets the due_back of the latest loan of the item to value'"""
        last_loan = Loan.objects.filter(item=self).latest("lent_on")
        last_loan.due_back = value

    @property
    def description(self) -> str:
        raise NotImplementedError


class BookInstance(Item):
    """Represents a copy of a book that is physically in the library"""

    def __str__(self):
        return f"[{self.label}] {self.book}"

    def get_absolute_url(self):
        """Returns the url to access a detail record for this bookInstance."""
        return reverse('library:bookInstance-detail', args=[str(self.id)])

    book = models.ForeignKey('Book', on_delete=models.RESTRICT, verbose_name=_('Book'))
    imprint = models.CharField(max_length=200, null=True, blank=True, verbose_name=_('Imprint'))

    class Meta:
        verbose_name=_('Book instance')
        verbose_name_plural=_('Book instances')
    @property
    def description(self) -> str:
        return str(self.book)



class MaterialInstance(Item):
    """Represents a instance of a material that is physically in the library"""

    def __str__(self):
        return f"[{self.label}] {self.material.name}"

    def get_absolute_url(self):

src/library/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from library.models import OpeningHours
from django.urls import reverse
from django.contrib.auth.models import User

class RenewItemForm(forms.Form):
    renewal_date = forms.DateField(help_text=_("Enter a date between now and 4 weeks (default 3)."))

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


class OpeningHoursModelForm(ModelForm):
    class Meta:
        model = OpeningHours
        fields = ['weekday', 'from_hour', 'to_hour']
        labels = {'from_hour': _('Open from'),
                  'to_hour': _('Open until')}

    def clean_hours(self):
        data = self.cleaned_data

        # Check if opening is before closing
        if data['from_hour'] > data['to_hour']:
            raise ValidationError(_('Library must be open before closing 😉'))

        return data

class UserSearchForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']
    use_required_attribute = False

src/library/api/views.py
from django.contrib.auth.models import User
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions
from library.models import Book, Member, Room
from .serializers import BookSerializer, AccessSerializer, Access


class BookApiView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, *args, **kwargs):
        """
        List all the books
        """
        books = Book.objects.all()
        serializer = BookSerializer(books, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request, *args, **kwargs):
        """
        Create the book
        """
        data = {
            'title': request.data.get('title'),
        }
        serializer = BookSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class AccessControlApiView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, *args, **kwargs):
        """
        Check if a user has permission to access room
        """
        user = Member.objects.get(UID=kwargs["uk"]).user
        access_bool = Room.objects.get(id=kwargs["rk"]).check_access(user)
        access = Access(access_bool)
        serializer = AccessSerializer(access)
        if access_bool:
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response(serializer.data, status=status.HTTP_401_UNAUTHORIZED)

src/library/templates/library/author.html
{% extends "library/base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Author" %}: {{ author }}</h1>
    <p><strong>{% translate "Date of birth" %}: </strong> {{ author.date_of_birth }}</p>

    <div style="margin-left:20px;margin-top:20px">
        {% if author.book_set.all %}
            <h4>{% translate "Books by this author" %}</h4>

            {% for book in author.book_set.all %}
                <hr>
                <p><strong><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></strong></p>
            {% endfor %}

        {% else %}
            <p>{% translate "No books by this author." %}</p>
        {% endif %}
    </div>
    {% if perms.author.can_change %}
        <div class="link-button"><a href="{% url "library:author-update" author.id %}">{% translate "Change Author" %}</a></div>
    {% endif %}
    {% if perms.author.can_delete %}
        <div class="link-button delete-button"><a href="{% url "library:author-delete" author.id %}">{% translate "Delete Author" %}</a>
        </div>
    {% endif %}
{% endblock %}

src/library/templates/library/author_form.html
{% extends "library/base_generic.html" %}
{% load i18n %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value={% translate "Submit" %}>
  </form>
{% endblock %}

src/library/templates/library/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>ILMO</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'library/css/styles.css' %}">
    <link href="{% static 'library/Font-Awesome/css/all.min.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
{% block header %}
    {% include "library/header.html" %}
{% endblock %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                {% include "library/nav_sidebar.html" %}
            {% endblock %}
        </div>
        <div class="col-sm-10 content-box">{% block content %}{% endblock %}{% block pagination %}
            {% if is_paginated %}
                <div class="pagination">
				<span class="page-links">
					{% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
						Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
					</span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
				</span>
                </div>
            {% endif %}
        {% endblock %}</div>

    </div>
</div>
</body>
</html>

src/library/templates/library/bookInstanceTable.html
{% load i18n %}
<table>
    <tr>
        <th>{% translate "Label" %}</th>
        <th>{% translate "Title" %}</th>
        <th>{% translate "Status" %}</th>
        <th>{% translate "Borrow/Return" %}</th>
    </tr>
    {% for book_instance in book_instances %}
        <tr>
            <td>{{ book_instance.label }}</td>
            <td>{{ book_instance.book.title }}</td>
            <td class="{% if book_instance.status == 'a' %}text-success{% elif book_instance.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ book_instance.get_status_display }}
            </td>
            <td>
                {% if book_instance.status == "a" %}
                    <a href="{% url 'library:item-borrow' book_instance.id %}">{% translate "Borrow" %}</a>
                {% elif book_instance.status == "o" %}
                    <a href="{% url 'library:item-return' book_instance.id %}">{% translate "Return" %}</a>
                {% else %}
                    {% translate "Unavailable" %}
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>

src/library/templates/library/bookTable.html
{% load custom_tags %}
{% load i18n %}
<table>
    <tr>
        <th>{% translate "Title" %}</th>
        <th>{% translate "Author" %}</th>
    </tr>
    {% for book in books %}
        <tr>
            <td><b><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></b></td>
            <td>{{ book.author.all|join_link:", " | safe }}</td>
        </tr>
    {% endfor %}
</table>

src/library/templates/library/item-search.html
{% extends "library/base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Search for an item by label" %}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="q">
        <input type="submit" value={% translate "Search" %}>
    </form>
    <div class="item_search_result">
        <table>
            <tr>
                <th>{% translate "Label" %}</th>
                <th>{% translate "Status" %}</th>
                <th>{% translate "Borrow" %}?</th>
            </tr>
            {% for item in items %}
                <tr>
                    <td>{{ item.label }}</td>
                    <td class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                        {{ item.get_status_display }}
                    </td>
                    <td><a href="{% url 'library:item-borrow' item.id %}">{% translate "Borrow" %}</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

src/library/templates/library/list_loans_user.html
{% extends "library/base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Borrowed books" %}</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{{  bookinst.get_absolute_url }}">{{bookinst}}</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>{% translate "There are no books borrowed." %}</p>
    {% endif %}

    <h1>{% translate "Borrowed material" %}</h1>

    {% if materialinstance_list %}
    <ul>

      {% for materialinst in materialinstance_list %}
      <li class="{% if materialinst.is_overdue %}text-danger{% endif %}">
        <a href="{{  materialinst.get_absolute_url }}">{{materialinst}}</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>{% translate "There are no materials borrowed." %}</p>
    {% endif %}
{% endblock %}

src/library/templates/library/loan-detail.html
{% extends "library/base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% translate "Loan" %}: {{ loan }}</h1>
    <p class="{% if loan.is_overdue is False %}text-success{% else %}text-warning{% endif %}">
        {{ loan.due_back }}
    </p>
    {% if loan.returned %}
        <p><strong>{% translate "Returned on" %}:</strong> {{ loan.returned_on }}</p>
    {% else %}
        <p><strong{% translate "Due to be returned" %}:</strong> {{ loan.due_back }}</p>
    {% endif %}
    {% if perms.library.can_see_borrowed %}
        <p><strong>{% translate "Borrowed by" %}: </strong>
            <a href="{{ loan.borrower.get_absolute_url }}"> {{ loan.borrower}} </a></p>
    {% endif %}
    {% if not loan.returned and perms.library.can_mark_returned %}
        <p><a href="{% url 'library:renew-item-librarian' loan.item.id %}">Renew</a></p>
    {% endif %}
  <p class="text-muted"><strong>{% translate "Id" %}:</strong> {{ loan.id }}</p>
{% endblock %}

src/library/templates/library/loan_book_table.html
<table>
    <tr>
    <th>Label</th>
    <th>Title</th>
    <th>Borrower</th>
    <th>Due</th>
    {% if perms.library.can_mark_returned %}
    <th>Change status</th>
    {% endif %}


    </tr>
    {% for bookinst in bookinstance_list %}
        <tr class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <td><a href="{% url 'library:bookInstance-detail' bookinst.pk %}">{{ bookinst.label }}</a></td>
            <td>{{ bookinst.book.title }}</td>
            <td>{{ bookinst.borrower }}</td>
            <td>{{ bookinst.due_back }}</td>
            {% if perms.library.can_mark_returned %}
            <td><a href="{% url 'library:renew-item-librarian' bookinst.id %}">Renew</a></td>
            {% endif %}


        </tr>
    {% endfor %}
</table>

src/library/templates/library/materialTable.html
{% load i18n %}
<table>
    <tr>
        <th>{% translate "Name" %}</th>
    </tr>
    {% for material in materials %}
        <tr>
            <td><b><a href="{{ material.get_absolute_url }}">{{ material.name }}</a></b></td>
        </tr>
    {% endfor %}
</table>

src/library/templates/library/member.html
{% extends "library/base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{{ member.user.get_full_name }}</h1>

    <p><strong>{% translate "Username" %}:</strong> {{ member.user.username }}</p>
    <p><strong>{% translate "E-Mail" %}:</strong> {{ member.user.email }}</p>

    {% if member.preferred_language %}
        <p><strong>{% translate "Language" %}:</strong> {{ member.preferred_language }}</p>
    {% else %}
        <p>{% translate "No preferred language set." %}</p>
    {% endif %}
    {% if member.UID %}
        <p><strong>{% translate "UID" %}:</strong> {{ member.UID }}</p>
    {% else %}
        <p>{% translate "No UID set." %}</p>
    {% endif %}
    {% if token %}
        <form action="" method="POST">
            {% csrf_token %}
            <p class="text-muted"><strong>{% translate "API token:" %}</strong> {{ token }}</p>
            <input class="create-token" type="submit" name="delete_token" value={% translate "Delete API token" %}>
        </form>
    {% else %}
        <p>{% translate "No token set." %}</p>
        <form action="" method="POST">
            {% csrf_token %}
            <input class="create-token" type="submit" name="create_token" value={% translate "Create API token" %}>
        </form>
    {% endif %}

{% endblock %}

src/library/templates/library/openinghour_confirm_delete.html
{% extends "library/base_generic.html" %}
{% load i18n %}

{% block content %}

<h1>Delete Opening Hour</h1>

<p>Are you sure you want to delete the opening hour: <i>{{ openinghours }}</i>?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class="delete-button" type="submit" value={% translate "Yes, delete." %}>
</form>

{% endblock %}

src/library/templates/library/openinghours.html
{% extends "library/base_generic.html" %}
{% load i18n %}

{% block content %}
	{% if openinghours_list %}
        <table>
            <th>{% translate "Weekday" %}</th>
            <th>{% translate "Open from" %}</th>
            <th>{% translate "Open until" %}</th>
            <th>{% translate "Comment" %}</th>
            {% if perms.library.change_opening_hours %}
                <th>{% translate "Delete" %}</th>
            {% endif %}
            {% for openinghour in openinghours_list %}
            <tr>
                <td>{{ openinghour.get_weekday_display }}</td>
                <td>{{ openinghour.to_hour }}</td>
                <td>{{ openinghour.from_hour }}</td>
                <td>{{ openinghour.comment }}</td>
                {% if perms.library.change_opening_hours %}
                    <td><a href="{% url "library:openinghour-delete" openinghour.id %} ">{% translate "Delete" %}</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
	{% else %}
		<p>{% translate "No opening hours are available." %}</p>
	{% endif %}
    {%   if perms.library.change_opening_hours %}
        <div class="link-button"><a  href="{% url "library:openinghour-create" %}" >{% translate "Create new opening hour" %}</a></div>
    {% endif %}
{% endblock %}

src/library/templates/library/userTable.html
{% load i18n %}
<table>
    <tr>
        <th>{% translate "Username" %}</th>
        <th>{% translate "First name" %}</th>
        <th>{% translate "Last name" %}</th>
    </tr>
    {% for user in user_list %}
        <tr>
            <td><b><a href="{% url 'library:user-detail' user.pk %}">{{ user.username }}</a></b></td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
        </tr>
    {% endfor %}
</table>